name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: String1Example test
      id: string1example-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: String1Example test
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        STRING1EXAMPLE-TEST_RESULTS: "${{steps.string1example-test.outputs.result}}"
      with:
        runners: string1example-test
